language: python
matrix:
    include:
        # Use the built in venv for linux builds
        - os: linux
          python: 3.5
          dist: trusty
        # Use generic language for osx
        - os: osx
          language: 3.5
script:
    - bash ./script/install-tests.sh
    - python ./script/download-tests.py $GH_TOKEN
    - python ./script/test.py
after_success:
    -  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash <(curl -s https://codecov.io/bash) ; fi