sudo: required
os:
  - linux
  - osx
dist: trusty
language: python
python:
  - 3.5
install:
    - chmod +x install-tests.sh
script:
    - ./install-tests.sh
    - python download-tests.py
    - test.sh