platform:
  - Win32
environment:
    PYTHON: "C:\\Python35"
build: off
install:
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
before_test:
    - ./script/install-tests.bat
    - python ./script/download-tests.py $GH_TOKEN
test_script:
    - python ./script/test.py