platform:
  - Win32
build: off
environment:
    matrix:
	    - PYTHON: "C:/Python35"
before_test:
    - cmd: ./install-tests.bat
    - cmd: %PYTHON% download-tests.py
test_script:
    - cmd: %PYTHON% test.py